/* 
 * File:   os5C.h
 * Author: Table 9
 *
 * Created on 28 septembre 2022, 16:34
 */

#ifndef OS5C_H
#define	OS5C_H

#define FCY 40000000
#define STATE_ATTENTE 0
#define STATE_ATTENTE_EN_COURS 1
#define STATE_AVANCE 2
#define STATE_AVANCE_EN_COURS 3
#define STATE_TOURNE_GAUCHE 4
#define STATE_TOURNE_GAUCHE_EN_COURS 5
#define STATE_LEGET_TOURNE_GAUCHE 18
#define STATE_LEGET_TOURNE_GAUCHE_EN_COURS 19
#define STATE_TOURNE_DROITE 6
#define STATE_TOURNE_DROITE_EN_COURS 7
#define STATE_LEGET_TOURNE_DROITE 20
#define STATE_LEGET_TOURNE_DROITE_EN_COURS 21
#define STATE_TOURNE_SUR_PLACE_GAUCHE 8
#define STATE_TOURNE_SUR_PLACE_GAUCHE_EN_COURS 9
#define STATE_TOURNE_SUR_PLACE_DROITE 10
#define STATE_TOURNE_SUR_PLACE_DROITE_EN_COURS 11
#define STATE_TOURNE_SUR_PLACE 16
#define STATE_TOURNE_SUR_PLACE_EN_COURS 17
#define STATE_ARRET 12
#define STATE_ARRET_EN_COURS 13

#define PAS_D_OBSTACLE 0
#define OBSTACLE_A_GAUCHE 1
#define OBSTACLE_A_DROITE 2
#define OBSTACLE_EN_FACE 3

void OperatingSystemLoop5C(void);
void SetNextRobotStateInAutomaticMode5C();

#ifdef	__cplusplus
extern "C" {
#endif




#ifdef	__cplusplus
}
#endif

#endif	/* OS5C_H */

